cash:            50000
core_etf:        "510300.SH"
bond_etf:        "511010.SH"
core_ratio:      0.60
bond_ratio:      0.10
alpha_ratio:     0.30
num_alpha:       8

# 风控
stop_loss:       0.12
take_profit:     0.10
max_drawdown:    0.08
trend_ma:        200

# 过滤
min_amount:      1e8
lot:             100
