# ===== 核心资产配比 =====
cash:            50000
core_etf:        "510300.SH"   # 沪深300 ETF
bond_etf:        "511010.SH"   # 10 年国债 ETF
core_ratio:      0.60          # 核心指数
bond_ratio:      0.10          # 债券缓冲
alpha_ratio:     0.30          # α 个股

num_alpha:       5             # α 仓股票数量

# ===== 风控参数 =====
stop_loss:       0.12          # 个股止损 12 %
max_drawdown:    0.08          # 组合回撤 8 %
trend_ma:        200           # 大盘趋势过滤 (200MA)

# ===== 其它 =====
min_amount:      1e8           # 个股成交额 ≥1 亿
lot:             100           # 股票最小成交单位
